//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_MAIN                        101
#define IDR_MENU1                       102
#define IDD_DECODE                      103
#define IDD_FILTERS                     104
#define IDI_ICON1                       107
#define IDD_ADAPTERS                    109
#define IDB_TOOLBAR                     110
#define IDR_MENU2                       112
#define IDD_RAW_DATA                    113
#define IDD_PROGRESS                    116
#define IDR_AVI2                        118
#define IDD_ABOUT                       119
#define IDR_MENU3                       125
#define IDB_DECODER                     126
#define IDD_REMOTECAPTURE               127
#define IDD_SERVER                      128
#define IDD_PRINT_STATUS                129
#define IDI_ICON2                       130
#define IDD_INPUT                       131
#define IDD_PACKET_TYPES                132
#define IDD_TYPE_PROPERTIES             133
#define IDD_PORTS                       134
#define IDD_DUMP                        135
#define IDR_AVI1                        136
#define IDD_DELETE                      137
#define IDD_LOGGING                     138
#define IDD_PACKETG                     139
#define IDR_MENU4                       140
#define IDD_DEBUG                       141
#define IDD_RULES                       142
#define IDD_TRACEROUTE                  148
#define IDD_HOSTLOOKUP                  149
#define IDD_PING                        150
#define IDB_CHECK                       151
#define IDB_CROSS                       152
#define IDI_COPY                        153
#define IDD_WHOIS                       154
#define IDD_PRINT_PREVIEW               155
#define IDC_LISTEN                      1002
#define ID_CLEAR                        1003
#define IDC_CLEAR                       1003
#define ID_CANCEL                       1005
#define ID_CLOSE                        1006
#define IDC_CHECK_UDP                   1007
#define IDC_CHECK_TCP                   1010
#define IDC_CHECK_ICMP                  1011
#define IDC_CHECK_ARP                   1012
#define IDC_CHECK_SRC_IP                1014
#define IDC_CHECK_DEST_IP               1015
#define IDC_EDIT_SRC_IP                 1016
#define IDC_EDIT_DEST_IP                1017
#define IDC_CHECK_PORT                  1018
#define IDC_EDIT_PORT                   1019
#define IDC_PREVIOUS                    1022
#define IDC_RAW                         1023
#define IDC_NEXT                        1024
#define IDC_EDIT_DATA                   1025
#define IDC_CHECK_IGMP                  1027
#define IDC_LIST1                       1028
#define IDC_MEDIUM                      1036
#define IDC_ADDRESS                     1037
#define IDC_FRAME_SIZE                  1038
#define IDC_LINK_SPEED                  1039
#define IDC_ANIMATE1                    1040
#define IDC_PROGRESS1                   1041
#define IDC_STATUS                      1042
#define IDC_HTML                        1043
#define IDC_EDIT_RAWDATA                1044
#define IDC_EDIT_IP                     1046
#define IDC_EDIT_PASSWORD               1048
#define ID_CONNECT                      1050
#define ID_CAPTURE                      1051
#define IDC_EDIT_USER                   1053
#define ID_MINIMIZE                     1055
#define IDC_STATUS2                     1057
#define IDC_LIST_DEBUG                  1058
#define IDC_EDIT_TIMEOUT                1059
#define IDC_SPIN1                       1060
#define IDC_PRINTER                     1061
#define IDC_CANCEL                      1062
#define IDC_LIST_SOURCE_IP              1063
#define IDC_LIST_DESTINATION_IP         1064
#define IDC_BUTTON_ADD_SOURCE           1067
#define IDC_BUTTON_REMOVE_SOURCE        1068
#define IDC_BUTTON_ADD_DESTINATION      1069
#define IDC_BUTTON_REMOVE_DESTINATION   1070
#define IDC_EDIT_INPUT                  1073
#define ID_OK                           1074
#define IDC_ADD                         1075
#define IDC_DELETE                      1076
#define IDC_EDIT                        1077
#define IDC_EDIT_NAME                   1078
#define IDC_LISTVIEW_ICONS              1079
#define IDC_LISTVIEW_FIELDS             1081
#define IDC_MOVE_UP                     1083
#define IDC_MOVE_DOWN                   1084
#define IDC_TREEVIEW                    1088
#define IDC_LISTVIEW                    1089
#define IDC_FIELD_ADD                   1091
#define IDC_FIELD_DELETE                1092
#define IDC_FIELD_EDIT                  1093
#define IDC_CHECK_UNKNOWN               1094
#define IDC_COMBO_PROTOCOL              1096
#define IDC_EDIT_LABEL                  1097
#define IDC_BUTTON_ADD                  1098
#define IDC_BUTTON_DELETE               1099
#define IDC_BUTTON_DISK                 1100
#define IDC_BUTTON_VIEW                 1101
#define IDC_BUTTON_CANCEL               1102
#define IDC_TEXT                        1103
#define IDC_CHECK_TIMESTAMP             1104
#define IDC_CHECK_SOURCE                1105
#define IDC_CHECK_DESTINATION           1106
#define IDC_CHECK_SIZE                  1107
#define IDC_CHECK_TYPE                  1108
#define IDC_CHECK_INFO                  1109
#define IDC_EDIT_FILESIZE               1110
#define IDC_EDIT_TEMP_DIRECTORY         1113
#define IDC_EDIT_SEQUENCE               1114
#define IDC_STATIC_JULIAN               1115
#define IDC_EDIT_FINAL_DIRECTORY        1116
#define IDC_TASK                        1117
#define IDC_PACKET_SIZE                 1118
#define IDC_SEND                        1121
#define IDC_SET                         1123
#define IDC_EDIT_DEBUG                  1125
#define IDC_RULE                        1126
#define IDC_CHECK_IDS                   1128
#define IDC_CHECK_FILTER                1129
#define IDC_LIST                        1132
#define IDC_SAVE                        1133
#define IDC_LIST_FORMAT                 1135
#define IDC_EDIT_COUNT                  1137
#define IDC_EDIT_BYTES                  1138
#define IDC_EDIT_THRUPUT                1139
#define IDC_EDIT_PEAK                   1140
#define IDC_EDIT_TIME                   1141
#define IDC_CHECK_ENABLE                1143
#define ID_TRACE                        1146
#define IDC_COMBO_HOSTS                 1148
#define IDC_COMBO_HOSTNAMES             1149
#define ID_RESOLVE                      1150
#define IDC_EDIT_OFFICIALNAME           1151
#define IDC_EDIT_ALIASES                1152
#define IDC_EDIT_ADDRESSES              1153
#define ID_PING                         1154
#define IDC_NUM                         1156
#define IDC_COPY                        1158
#define IDC_COMBO_DOMAINS               1160
#define IDC_COMBO_SERVERS               1163
#define ID_LOOKUP                       1165
#define IDC_EDIT_RESULT                 1166
#define IDC_CLOSE                       1169
#define IDC_RADIO_FILTER                1170
#define IDC_RADIO_NOFILTER              1171
#define IDC_EDIT_USERNAME               1172
#define IDC_EDIT_REGKEY                 1173
#define IDC_REGISTER                    1174
#define IDC_MOVEUP                      1175
#define IDC_MOVEDOWN                    1176
#define IDC_DEFAULT                     1177
#define IDC_BUY                         1178
#define iWSAEINTR                       10004
#define iWSAEBADF                       10009
#define iWSAEACCES                      10013
#define iWSAEFAULT                      10014
#define iWSAEINVAL                      10022
#define iWSAEMFILE                      10024
#define iWSAEWOULDBLOCK                 10035
#define iWSAEINPROGRESS                 10036
#define iWSAEALREADY                    10037
#define iWSAENOTSOCK                    10038
#define iWSAEDESTADDRREQ                10039
#define iWSAEMSGSIZE                    10040
#define iWSAEPROTOTYPE                  10041
#define iWSAENOPROTOOPT                 10042
#define iWSAEPROTONOSUPPORT             10043
#define iWSAESOCKTNOSUPPORT             10044
#define iWSAEOPNOTSUPP                  10045
#define iWSAEPFNOSUPPORT                10046
#define iWSAEAFNOSUPPORT                10047
#define iWSAEADDRINUSE                  10048
#define iWSAEADDRNOTAVAIL               10049
#define iWSAENETDOWN                    10050
#define iWSAENETUNREACH                 10051
#define iWSAENETRESET                   10052
#define iWSAECONNABORTED                10053
#define iWSAECONNRESET                  10054
#define iWSAENOBUFS                     10055
#define iWSAEISCONN                     10056
#define iWSAENOTCONN                    10057
#define iWSAESHUTDOWN                   10058
#define iWSAETOOMANYREFS                10059
#define iWSAETIMEDOUT                   10060
#define iWSAECONNREFUSED                10061
#define iWSAELOOP                       10062
#define iWSAENAMETOOLONG                10063
#define iWSAEHOSTDOWN                   10064
#define iWSAEHOSTUNREACH                10065
#define iWSASYSNOTREADY                 10091
#define iWSAVERNOTSUPPORTED             10092
#define iWSANOTINITIALISED              10093
#define iWSAHOST_NOT_FOUND              11001
#define iWSATRY_AGAIN                   11002
#define iWSANO_RECOVERY                 11003
#define iWSANO_DATA                     11004
#define IDM_EXIT                        40001
#define IDC_EXIT                        40001
#define ID_START                        40002
#define ID_STOP                         40003
#define IDC_STOP                        40003
#define IDM_FILTERS                     40004
#define IDC_FILTERS                     40004
#define ID_ADAPTER                      40005
#define IDC_ADAPTER                     40005
#define ID_ARP_WATCH                    40006
#define ID_INTERNET_MANIAC              40007
#define ID_TOOLS_BANDWIDTH              40008
#define IDC_DECODE                      40009
#define IDC_ONLINE_HELP                 40010
#define IDC_ABOUT                       40011
#define IDC_DUMP_ALL                    40016
#define IDC_RAW_DATA                    40017
#define IDC_SAVE_BINARY                 40018
#define ID_PACKET_GENERATOR             40019
#define IDC_BUFFER                      40020
#define ID_OPTIONS_BUFFERDUMP           40020
#define ID_PACKET_NEXT                  40021
#define ID_PACKET_PREVIOUS              40022
#define ID_FILE_OPENSESSION             40023
#define ID_FILE_IMPORT                  40023
#define ID_FILE_SAVESESSION             40024
#define ID_FILE_EXPORT                  40024
#define ID_OPEN                         40026
#define ID_SAVE                         40027
#define ID_PRINT_DLG                    40028
#define IDC_REMOTE                      40029
#define ID_OPTIONS_SERVERMODE           40030
#define ID_PRINT                        40031
#define IDC_PACKET_TYPES                40032
#define ID_OPTIONS_PORTS                40033
#define ID_OPTIONS_LOGGINGMODE          40034
#define ID_OPTIONS_NORMALMODE           40035
#define ID_OPTIONS_LOGGING              40036
#define ID_ACTION_RESOLVEIPS            40037
#define IDC_OPEN_PACKET                 40040
#define IDC_SAVE_PACKET                 40041
#define IDC_PACKETGEN                   40043
#define ID_OPTIONS_MANAGERULES          40044
#define ID_TOOLS_TRACEROUTE             40045
#define ID_TOOLS_PING                   40046
#define ID_TOOLS_WHOIS                  40047
#define ID_TOOLS_HOSTLOOKUP             40049
#define ID_POPUP_SOURCEIP_DNSLOOKUP     40058
#define ID_POPUP_SOURCEIP_PING          40059
#define ID_POPUP_SOURCEIP_TRACEROUTE    40060
#define ID_POPUP_SOURCEIP_WHOIS         40061
#define ID_POPUP_DESTINATIONIP_DNSLOOKUP 40062
#define ID_POPUP_DESTINATIONIP_PING     40063
#define ID_POPUP_DESTINATIONIP_TRACEROUTE 40064
#define ID_POPUP_DESTINATIONIP_WHOIS    40065
#define ID_PRINT_PREVIEW                40066
#define ID_TOOLS_DEBUG                  40067

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         40068
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
